drop table  book;
create table book(title text, author text, publish text);
insert into book values('パソコンインターフェース考','佐藤清忠','ＣＱ出版');
insert into book values('ＭＳ−ＤＯＳプレイングマニュアル    ＰＬＡＹＩＮＧ①','島本笹清','ＪＩＣＣ出版局');
insert into book values('Ｂａｓｉｃ  ｅｌｅｃｔｒｏｎｉｃｓ  ｆｏｒ  ｓｃｉｅｎｔｉｓｔｓ．','Ｂｒｏｐｈｙ，Ｊ．Ｊ．','ＭｃＧｒａｗ−Ｈｉ');
insert into book values('超人工知能','石原藤夫  金子隆一','ＰＨＰ研究所');
insert into book values('日本の挑戦  第五世代コンピュータ','ファイゲンバウム，エドワード  他','ＴＢＳブリタニカ');
insert into book values('Ｉｎｓｉｄｅ  Ｍａｃｉｎｔｏｓｈ  Ｖｏｌｕｍｅｓ  Ⅲ＆Ⅳ  （日本語版）','Ａｐｐｌｅ  Ｃｏｍｐｕｔｅｒ，Ｉｎｃ．','アジソンウェスレイ');
insert into book values('Ｉｎｓｉｄｅ  Ｍａｃｉｎｔｏｓｈ  Ｖｏｌ．Ⅰ＆Ⅱ  （日本語版）','Ａｐｐｌｅ  Ｃｏｍｐｕｔｅｒ，Ｉｎｃ．','アジソンウェスレイ');
insert into book values('標準ＭＳ−ＤＯＳハンドブック','アスキー出版局  編著','アスキー');
insert into book values('入門  グラフィックス  アスキー・ラーニングシステム１  入門コース','佐藤義雄','アスキー');
insert into book values('入門  グラフィックス  アスキー・ラーニングシステム１  入門コース','佐藤義雄','アスキー');
insert into book values('Ｍａｃｉｎｔｏｓｈ','Ｌｕ，Ｃ．','アスキー');
insert into book values('純粋人工知能批判','ドレイファス，Ｈ．Ｌ．  他','アスキー');
insert into book values('アートとしてのソフトウェア','ヘッケル，Ｐ．','アスキー');
insert into book values('ＵＮＩＸワークステーション  ＮＥＷＳ−ＯＳシステムワークブック','石田秋也  松前祐司  武居昌宏','アスキー');
insert into book values('ＭＳーＤＯＳを２５６倍使うための本  Ｖｏｌ．３','福崎俊博  山田伸一郎','アスキー');
insert into book values('Ｍｕｌｔｉｐｌａｎ２．０ブック','','アスキー');
insert into book values('プロフェッショナルＵＮＩＸ','村井純  井上尚司  砂原秀樹','アスキー');
insert into book values('実用  ＭＳ−ＤＯＳ  アスキー・ラーニングシステム２  実用コース','村瀬康治','アスキー');
insert into book values('ＵＮＩＸワークステーションＮＥＷＳ','井上尚司  大野浩之  柳楽直樹  他','アスキー出版局');
insert into book values('ＵＮＩＸワークステーション          ＮＥＷＳ−ＯＳシステムワークブック','石田秋也  松前祐司  武居昌宏','アスキー出版局');
insert into book values('ＵＮＩＸワークステーション          ＮＥＷＳ−ＯＳシステムワークブック','石田秋也  松前祐司  武居昌宏','アスキー出版局');
insert into book values('ＭＳ−ＤＯＳエンサイクロペディアVol.２  リファレンス編','マイクロソフトプレス  編','アスキー出版局');
insert into book values('ＭＳ−ＤＯＳを２５６倍使うための本  Ｖｏｌ．１','アスキー書籍編集部  編著','アスキー出版局');
insert into book values('ＭＳ−ＤＯＳを２５６倍使うための本  Ｖｏｌ．２','福崎俊博','アスキー出版局');
insert into book values('応用  グラフィックス  アスキー・ラーニングシステム３  応用コース','大田昌孝  竹内あきら  大口孝之','アスキー出版局');
insert into book values('勝手にＭＳ−ＤＯＳ！  とびきり実践的なＭＳ−ＤＯＳガイダンス','卯木孝一郎','アスキー出版局');
insert into book values('知識ベースシステム入門','村上憲郎','インフォメーション');
insert into book values('ＭＳ−ＤＯＳ  拡張ユーティリティ入門','','エー・アイ・ソフト');
insert into book values('続  ＭＳ−ＤＯＳ  拡張ユーティリティ入門','','エー・アイ・ソフト');
insert into book values('電波工学','榎本肇  関口利男','オーム社');
insert into book values('電気・電子・通信系のための基本電子技術','堀重雄','オーム社');
insert into book values('現代グラフ理論の基礎','前田渡  他','オーム社');
insert into book values('現代グラフ理論の基礎','前田渡  伊東正安','オーム社');
insert into book values('だれにでもわかる電子工学読本','中山章  薬袋馨  河崎隆一','オーム社');
insert into book values('量子エレクトロニクス  物性工学講座','宅間宏','オーム社');
insert into book values('壓電氣と高周波','古賀逸策','オーム社');
insert into book values('現代無線通信工学','河野政治','オーム社');
insert into book values('絵ときコンピュータ','大谷忠雄','オーム社');
insert into book values('オプトエレクトロニクス入門','後藤顕也','オーム社');
insert into book values('オプトエレクトロニクス入門','後藤顕也','オーム社');
insert into book values('現代電気電子工学の基礎実験','元岡達  編','オーム社');
insert into book values('パソコン・グラフィクスエレクトロニクス','伊賀健一  武者利光','オーム社');
insert into book values('初級電子工学','中山章','オーム社');
insert into book values('無線工学','谷村功','オーム社');
insert into book values('無線工学ハンドブック  １９５４','日本電波協会','オーム社');
insert into book values('音響科学','八木秀次  編','オーム社');
insert into book values('電子工学ポケットブック','','オーム社');
insert into book values('無線工学ハンドブック  １９５８','日本電波協会  編','オーム社');
insert into book values('ノモグラフの極意','竹内寿太郎','オーム社');
insert into book values('エレクトロニクス−基礎と応用−','阿部善右衛門  村田裕  中添淳','オーム社');
insert into book values('計算基礎論','足立暁生','オーム社');
insert into book values('コンピュータアーキテクチャ          知識工学講座７','雨宮真人  田中譲','オーム社');
insert into book values('パワーエレクトロニクスとシステム制御','安部可治  編著','オーム社');
insert into book values('図解  ３２ビットマイクロプロセッサＭＣ６８０２０','朝日廣治  外園寛実  國岡保康','オーム社');
insert into book values('知識工学','情報処理学会  編','オーム社');
insert into book values('新版  無線工学ハンドブック','星合正治','オーム社');
insert into book values('１種ソフトウェア','','オーム社');
insert into book values('マイクロ波機器・電波航法','金田秀夫','オーム社');
insert into book values('電子工学入門','元田益太郎','オーム社');
insert into book values('無線機器                            二技二通受験講座','錦織博介','オーム社');
insert into book values('情報基礎論                          情報工学基礎講座１','長尾真  辻井潤一  山崎進','オーム社');
insert into book values('無線機器                            二技二通受験講座','錦織博介','オーム社');
insert into book values('ライフサイエンスを測る  超音波・画像・光計測入門','佐下橋市太郎  寺西昭男  橋本康  他','オーム社');
insert into book values('無線測定                            二技二通受験講座','大村保','オーム社');
insert into book values('初歩の電子読本','小沢彰  国分里美','オーム社');
insert into book values('大学課程  電子管工学','岡村総吾','オーム社');
insert into book values('無線工学の基礎Ⅱ                    二技二通受験講座','斎藤博','オーム社');
insert into book values('無線工学の基礎Ⅴ                    二技二通受験講座','園山重道','オーム社');
insert into book values('無線工学の基礎Ⅴ                    二技二通受験講座','園山重道','オーム社');
insert into book values('情報科学の基礎研究','坂井利之  編','オーム社');
insert into book values('ＣＴＲＯＮ概説                      原典ＣＴＲＯＮ大系１','トロン協会ＣＴＲＯＮ専門委員会  編','オーム社');
insert into book values('人工知能                            新ＯＨＭ文庫','志村正道','オーム社');
insert into book values('入門  ソフトウェア','高橋守清','オーム社');
insert into book values('エキスパートシステム                知識工学講座５','上野晴樹  小山照夫  編','オーム社');
insert into book values('知識工学入門  改訂２版','上野晴樹','オーム社');
insert into book values('知識工学入門','上野晴樹','オーム社');
insert into book values('図解  分散知識処理入門','山崎晴明  宮崎収兄','オーム社');
insert into book values('第５世代コンピュータ','横井俊夫','オーム社');
insert into book values('現代グラフ理論の基礎','前田渡  伊藤正安','オ−ム社');
insert into book values('現代無線通信工学','河野政治','オ−ム社');
insert into book values('電波応用','岡田實  谷村功  堀井隆','コロナ社');
insert into book values('電波応用','岡田實  谷村功  堀井隆','コロナ社');
insert into book values('電波応用  電子通信学会大学講座２６','岡田實  谷村功  堀井隆','コロナ社');
insert into book values('電話級・電信級  アマチュア無線工学','藤津實','コロナ社');
insert into book values('電波工学                            新編電子工学講座１８','阿座上孝  橋本礼治','コロナ社');
insert into book values('ディジタル制御技術の基礎','市川邦彦','コロナ社');
insert into book values('騒音・振動（上）  音響工学講座４','五十嵐寿一  他','コロナ社');
insert into book values('電子応用','小西重成  村上正夫','コロナ社');
insert into book values('電波工学例題演習  標準電気電子工学例題演習シリーズ８','虫明康人  安達三郎','コロナ社');
insert into book values('電波工学例題演習','虫明康人  安達三郎','コロナ社');
insert into book values('電子管工学Ⅰ  電子通信学会大学講座２','岡村総吾  林友直','コロナ社');
insert into book values('電子管工学Ⅲ  電子通信学会大学講座４','山本賢三  長谷部堅陸','コロナ社');
insert into book values('振動學入門','バルクハウゼン','コロナ社');
insert into book values('電子工学                            新編電子工学講座１３','西村信雄  落山謙三','コロナ社');
insert into book values('電子工学','西村信雄  落山謙三','コロナ社');
insert into book values('グラフ理論  現代応用数学講座','尾崎弘  白川功  翁長健治','コロナ社');
insert into book values('グラフ理論','尾崎弘  他','コロナ社');
insert into book values('電子工学  改訂版','石黒美種  牛田富之','コロナ社');
insert into book values('電子工学  改訂版  標準電気工学講座１５','石黒美種  牛田富之','コロナ社');
insert into book values('電子工学  改訂版','石黒美種  牛田富之','コロナ社');
insert into book values('無線通信工学  電子通信学会大学講座２１','電子通信学会  編','コロナ社');
insert into book values('無線通信工学','谷村功','コロナ社');
insert into book values('無線通信工学  電子通信学会大学講座２０','谷村功','コロナ社');
insert into book values('応用電子工学概論  電子通信学会大学講座３２','池上淳一  近藤文治','コロナ社');
insert into book values('応用電子工学概論','電子通信学会  編','コロナ社');
insert into book values('演習  グラフ理論','伊理正夫  他','コロナ社');
insert into book values('演習  グラフ理論','伊理正夫  他','コロナ社');
insert into book values('無線工学の理論と実際','Ｌ．Ｓ．パーマー','コロナ社');
insert into book values('固体電子工学','和田正信  中野朝安','コロナ社');
insert into book values('量子エレクトロニクス','電子通信学会  編','コロナ社');
insert into book values('電子工学Ⅱ  トレーニングノート','中山章  他','コロナ社');
insert into book values('電子応用  電子通信学会大学講座２８','熊谷三郎  中西義郎','コロナ社');
insert into book values('コンピュートロール№１０  特集  知識情報処理','','コロナ社');
insert into book values('電子応用','小西重成  他','コロナ社');
insert into book values('工学系学生のエレクトロニクス通論','都筑泰雄  土肥康孝','コロナ社');
insert into book values('基礎  電子技術','電子技術研究会  編','コロナ社');
insert into book values('基礎  電子技術','電子技術研究会  編','コロナ社');
insert into book values('電子工学例題演習','石黒美種  牛田富之','コロナ社');
insert into book values('電子工学例題演習','石黒美種  牛田富之','コロナ社');
insert into book values('電子工学概論','相川孝作','コロナ社');
insert into book values('電子工学概論','相川孝作','コロナ社');
insert into book values('計算図表・図式計算法  応用数学講座第６巻','本間仁  内田茂男','コロナ社');
insert into book values('計算図表・図式計算法  応用数学講座第６巻','本間仁  内田茂男','コロナ社');
insert into book values('演習  グラフ理論  基礎と応用','伊理正夫  白川功  梶谷洋司  篠田庄司  他','コロナ社');
insert into book values('標準電気工学講座１５  電子工学  改訂','石黒美種  他','コロナ社');
insert into book values('標準電気工学講座１５  電子工学  改訂','石黒美種  他','コロナ社');
insert into book values('標準電気工学講座１５  電子工学  改訂','石黒美種  他','コロナ社');
insert into book values('電子工学','石黒美種  牛田富之','コロナ社');
insert into book values('電子工学','石黒美種','コロナ社');
insert into book values('電子工学','石黒美種','コロナ社');
insert into book values('電子応用','熊谷三郎  中西義郎','コロナ社');
insert into book values('コンピュートロール  №９','花房秀郎  編集','コロナ社');
insert into book values('コンピュートロール№１０  特集  知識情報処理','','コロナ社');
insert into book values('わかりやすい計算尺理論','前田明雄','コロナ社');
insert into book values('アンテナ、電波伝搬','虫明康人','コロナ社');
insert into book values('画像と言語の認識工学              エレクトロニクスモノグラフシリーズ２','長尾真','コロナ社');
insert into book values('画像と言語の認識工学          エレクトロニクスモノグラフシリーズ２','長尾真','コロナ社');
insert into book values('電子管工学（Ⅰ）','岡村総吾  林友直','コロナ社');
insert into book values('電波応用','岡田実  谷村功','コロナ社');
insert into book values('情報基礎学詳説','坂井利之  編著','コロナ社');
insert into book values('情報基礎学演習','坂井利之','コロナ社');
insert into book values('光デバイス演習                      電子情報通信学会大学シリーズ３２','末松安晴  上林利生','コロナ社');
insert into book values('コンピュートロール№２９','','コロナ社');
insert into book values('無線通信工学                        電子通信学会大学講座２１','谷村功','コロナ社');
insert into book values('無線通信工学                        電子通信学会大学講座２１','谷村功','コロナ社');
insert into book values('無線通信工学','谷村功','コロナ社');
insert into book values('計算尺の手引','山口恭','コロナ社');
insert into book values('計算尺の操作と応用','山口恭','コロナ社');
insert into book values('計算尺の操作と応用','山口恭','コロナ社');
insert into book values('線形系の理論','Ｌ．Ａ．Ｚａｄｅｈ  Ｃ．Ａ．Ｄｅｓｏｅｒ','コロナ社');
insert into book values('コンピューター利用の座標軸  変わるコンピューター、変わらぬ組織','名和小太郎','コンピュータ・エー');
insert into book values('計算機科学入門','アービブ，Ｍ．  クフォーリ，Ａ．  他','サイエンス社');
insert into book values('日本語ＭＳ−ＤＯＳ入門  パソコン・ソフトウェア８','荒木康匡','サイエンス社');
insert into book values('人工知能と人間Ⅰ','ボーデン，Ｍ．Ａ．','サイエンス社');
insert into book values('人工知能と人間Ⅱ','ボーデン，Ｍ．Ａ．','サイエンス社');
insert into book values('フラクタルＣＧコレクション','渕上季代絵','サイエンス社');
insert into book values('コンピュータ英語の読み方','一松信','サイエンス社');
insert into book values('認知科学入門','戸田正直  他','サイエンス社');
insert into book values('工学基礎  振動論  ライブラリ工学基礎３','徳岡辰雄','サイエンス社');
insert into book values('海外情報源ハンドブック','ジャパンタイムズ  編','ジャパンタイムズ');
insert into book values('考えるコンピュータ','シャンク，Ｒ．Ｃ．','ダイヤモンド社');
insert into book values('使えるかなＵＮＩＸ','村井純','テクノ');
insert into book values('ＢＡＳＩＣ，Ｃ，８０８６，ＭＳ−ＤＯＳ，ＵＮＩＸによる９８ソフトウェア','河西朝雄','ナツメ社');
insert into book values('ＭＳ−ＤＯＳまかせの実用バッチファイル集  すぐに使える８８本！','藤田英時','ナツメ社');
insert into book values('ＭＳ−ＤＯＳ拡張バッチファイル入門','肥田野登','ナツメ社');
insert into book values('ＭＳ−ＤＯＳ  システムコールハンドブック','河西朝雄','ナツメ社');
insert into book values('ＭＳ−ＤＯＳ構造解析','押野崇芳','ナツメ社');
insert into book values('いちばんやさしいＭＳ−ＤＯＳ入門','小澤眞樹  柏木歩','ナツメ社');
insert into book values('ＭＳ−ＤＯＳハンドブック','酒井雄二郎  葛井真作  阿部友計','ナツメ社');
insert into book values('ＭＳ−ＤＯＳ強化コマンド集  Ｃ言語プログラミングによる','吉野敏也','ナツメ社');
insert into book values('ＧＫＳ入門','マッケイ，ルシア','ノバグラフィックス');
insert into book values('横振り電鍵のすべて','大倉秋四郎','ハモンドエレクトロ');
insert into book values('横振り電鍵のすべて','大倉秋四郎','ハモンドエレクトロ');
insert into book values('横振り電鍵のすべて','大倉秋四郎','ハモンドエレクトロ');
insert into book values('マッキントッシュの道具箱  Ｖｏｌ．１','チェルニコフ，スティーブ','パーソナルメディア');
insert into book values('マッキントッシュの道具箱  Ｖｏｌ．２','チェルニコフ，スティーブ','パーソナルメディア');
insert into book values('ＭＩＴの人工知能','Ｗ．Ｅ．Ｌ．グリムソン  他  編','パーソナルメディア');
insert into book values('ＴＲＯＮプロジェクト’８７−’８８','坂村健  編','パーソナルメディア');
insert into book values('ＨｙｐｅｒＣａｒｄスタックウエアの作り方','鷲見正人','ビー・エヌ・エヌ');
insert into book values('現場マンのエレクトロニクス英語','篠原稔','ビジネス・オーム');
insert into book values('Ｃ・Ｇフォト・テクニック','宮入邦男  斎藤寛由','ビジネス・オーム');
insert into book values('電子計算機活用のための振動解析の理論と応用＜上＞','Ｌ．マイロヴィッチ','ブレイン図書出版');
insert into book values('電子計算機活用のための振動解析の理論と応用＜下＞','Ｌ．マイロヴィッチ','ブレイン図書出版');
insert into book values('情報力の研究','プレジデント  編','プレジデント社');
insert into book values('アルゴリズムとプログラムによるコンピュータグラフィックス［Ⅰ］','Ｓ．ハリントン','マグロウヒル');
insert into book values('アルゴリズムとプログラムによるコンピュータグラフィックス［Ⅱ］','Ｓ．ハリントン','マグロウヒル');
insert into book values('パーソナルコンピュータで学ぶＡＩとエキスパートシステム','Ｒ．Ｉ．Ｌｅｖｉｎｅ  他','マグロウヒル');
insert into book values('ランニングＭＳ−ＤＯＳ  実習によるＭＳ−ＤＯＳ入門','ウォルバートン，Ｖ．','マグロウヒル');
insert into book values('コンピュータグラフィックス','プラストック，Ｒ．Ｅ．  カレイ，Ｇ．','マグロウヒルブック');
insert into book values('コンピュータサイエンスのための組合せ構造とグラフ理論入門','リュー，Ｃ．Ｌ．','マグロウヒル好学社');
insert into book values('ディジタルシステム入門','バニスター，Ｂ．Ｒ．他','マグロウヒル好学社');
insert into book values('ソフトウェアの信頼性                ソフトウェア工学講座Ⅲ','Ｍ．Ｌ．シューマン','マグロウヒル出版');
insert into book values('アナログ・ディジタル技術入門','橋本順次  他','ラジオ技術社');
insert into book values('アナログ．ディジタル技術入門','','ラジオ技術社');
insert into book values('エレクトロ＝メカニカル機器  電子技術と機械技術をむすぶ','橋本順次','ラジオ技術社');
insert into book values('マイクロエレクトロニクスへの招待  これだけは知っておきたい現代教養','井内優','ラジオ技術社');
insert into book values('ＭＳ−ＤＯＳデータブック','幸田敏記','ラジオ技術社');
insert into book values('新しい電波技術（下）  無線通信編','新しい電波技術編集委員会  編','ラティス');
insert into book values('新しい電波技術上  放送・宇宙通信編','','ラティス');
insert into book values('新しい電波技術下  無線通信編','','ラティス');
insert into book values('無線通信（１）','新しい電波技術編集委員会  編','ラティス');
insert into book values('無線通信Ⅰ  新しい電波技術Ⅲ','新しい電波技術編集委員会  編','ラティス');
insert into book values('無線通信Ⅰ  新しい電波技術Ⅲ','新しい電波技術編集委員会  編','ラティス');
insert into book values('無線通信（２）','新しい電波技術編集委員会  編','ラティス');
insert into book values('無線通信Ⅱ  新しい電波技術Ⅳ','新しい電波技術編集委員会  編','ラティス');
insert into book values('無線通信Ⅱ  新しい電波技術Ⅳ','新しい電波技術編集委員会  編','ラティス');
insert into book values('無線通信（１）','新しい電波技術編集委員会  編','ラティス');
insert into book values('無線通信（２）','新しい電波技術編集委員会  編','ラティス');
insert into book values('放送','新しい電波技術編集委員会  編','ラティス');
insert into book values('放送  新しい電波技術Ⅱ','新しい電波技術編集委員会  編','ラティス');
insert into book values('放送  新しい電波技術Ⅱ','新しい電波技術編集委員会  編','ラティス');
insert into book values('放送','新しい電波技術編集委員会  編','ラティス');
insert into book values('電波計測・電波監理','新しい電波技術編集委員会  編','ラティス');
insert into book values('電波計測・電波監理','新しい電波技術編集委員会  編','ラティス');
insert into book values('電波計測・電波監理  新しい電波技術Ⅴ','新しい電波技術編集委員会  編','ラティス');
insert into book values('電波計測・電波監理  新しい電波技術Ⅴ','新しい電波技術編集委員会  編','ラティス');
insert into book values('新しい電波技術','郵政省電波管理局  編','ラティス社');
insert into book values('新しい電波技術（上）  放送・宇宙通信編','新しい電波技術編集委員会  編','ラテイス');
insert into book values('新しい電波技術（下）  無線通信編','新しい電波技術編集委員会  編','ラテイス');
insert into book values('計算尺の初歩から応用まで','高原健吉','永岡書店');
insert into book values('振動論','坪井忠二','河出書房');
insert into book values('最小自乗法，数値積分法，数値計算法','芝亀吉  他','河出書房');
insert into book values('音と光の世界','田口','河出書房');
insert into book values('音と楽器  波動と聴覚の基礎知識','ベナード，Ａ．Ｈ．','河出書房新社');
insert into book values('量子エレクトロニクス  メーザー・レーザー・トランジスター','ピアース，ジョン．Ｒ．','河出書房新社');
insert into book values('量子エレクトロニクス  新装版  現代の科学５','ピアース，ジョン．Ｒ．','河出書房新社');
insert into book values('量子エレクトロニクス  メーザー・レーザー・トランジスター','ピアース，ジョン．Ｒ．','河出書房新社');
insert into book values('電子と波  エレクトロニクスの基礎  現代の科学２３','ピアース，ジョン．Ｒ．','河出書房新社');
insert into book values('電子と波  エレクトロニクスの基礎  現代の科学３０','ピアース，ジョン．Ｒ．','河出書房新社');
insert into book values('電波工学演習','宇田新太郎','学献社');
insert into book values('電子工学Ⅰ  電気工学入門演習９','松森徳衛','学献社');
insert into book values('特選  グラフィックスデザイン','畠中兼司  北尾和信','学習研究社');
insert into book values('ＵＮＩＸ詳説  基礎編','井田正之','丸善');
insert into book values('電子量子工学の基礎','宇田新太郎','丸善');
insert into book values('電子・通信・電気工学実験Ⅰ  電子・通信電気工学基礎講座１９','福島弘毅  編','丸善');
insert into book values('電子・通信・電気工学基礎講座１９  電子・通信・電気工学実験Ⅰ','福島弘毅  編','丸善');
insert into book values('電子・通信・電気工学実験Ⅰ','福島弘毅  編','丸善');
insert into book values('電子・通信・電気工学基礎講座１９  電子・通信・電気工学実験Ⅱ','福島弘毅  編','丸善');
insert into book values('電子・通信・電気工学実験Ⅱ','福島弘毅  編','丸善');
insert into book values('光エレクトロニクスの基礎','Ｙａｒｉｖ，Ａｗｎｏｎ','丸善');
insert into book values('情報学概論','仲本秀四郎','丸善');
insert into book values('電子工学基礎論  電子・通信電気工学基礎講座９','西沢潤一  須藤建','丸善');
insert into book values('自然科学者のためのエレクトロニクス入門','米満澄','丸善');
insert into book values('電気・電子学生のための情報工学実験','伊藤誠','丸善');
insert into book values('電気・電子学生のための電波・電子応用','石井正博','丸善');
insert into book values('電気・電子学生のための電波・電子応用','石井正博','丸善');
insert into book values('新しい計算機アーキテクチャ','飯塚肇  編','丸善');
insert into book values('バイオエレクトロニクス','松本元  他  編','丸善');
insert into book values('自然言語の処理','高木朗  伊東幸宏','丸善');
insert into book values('新版  無線工学  伝送編','宇田新太郎','丸善');
insert into book values('新版  無線工学  エレクトロニクス編','宇田新太郎','丸善');
insert into book values('計算法及び計算器械','小平吉男','岩波書店');
insert into book values('彈性振動及び音響學','田丸卓郎','岩波書店');
insert into book values('音','小幡重一','岩波書店');
insert into book values('統計入門','松下嘉米男','岩波書店');
insert into book values('電子線','三宅静雄','岩波書店');
insert into book values('エレクトロニクスの話  ラジオから電子計算機まで','関英男','岩波書店');
insert into book values('マイクロエレクトロニクス革命  岩波現代新書ＮＳ','ジャック，Ｍ．Ａ．','岩波書店');
insert into book values('高等函数表','林桂一','岩波書店');
insert into book values('心をもつ機械','バーンスタイン，Ｊ．','岩波書店');
insert into book values('ＩＥＥＥソフトウェア’８８','ＩＥＥＥソフトウェア編集委員会  編','岩波書店');
insert into book values('確率論','末綱恕一','岩波書店');
insert into book values('人工知能とはなにか','白井良明','岩波書店');
insert into book values('人工知能とはなにか','白井良明','岩波書店');
insert into book values('コンピュータ入門','和田秀男','岩波書店');
insert into book values('ソフトウェアのテスト技術','Ｄｅｕｔｓｃｈ，Ｍ．Ｓ．','企画センター');
insert into book values('ＰＣ−９８０１−Ｅ−Ｆ  困った時に開く本','戸内順一','技術評論社');
insert into book values('ＰＣ−９８０１−Ｅ−Ｆ  困った時に開く本','戸内順一','技術評論社');
insert into book values('９８  ユーティリティ＆内部ルーチン解析','宮崎淳  角谷博孝','技術評論社');
insert into book values('パソコンのＵＮＩＸ','小幡広昭  木下貢史','技術評論社');
insert into book values('ＰＳ−２３２Ｃ通信ハンドブック  ＣＯＭ  ＢＯＯＫＳ１','システムサイエンス研究所','技術評論社');
insert into book values('入門と実習  ニューロコンピュータ','中野馨  飯沼一元  他','技術評論社');
insert into book values('はじめての電子工作','前田光男  山賀弘','技術評論社');
insert into book values('シリアル伝送技術入門','伊藤久雄','技術評論社');
insert into book values('超高速エディタＦＩＮＡＬ','宍倉幸則','技術評論社');
insert into book values('初級  マイクロコンピュタ応用システム開発技術者試験  上巻  ６２年版','','技術評論社');
insert into book values('パソコン・インターフェースの制作実習','横山直隆','技術評論社');
insert into book values('パソコン・インターフェースの製作実習  Ｈａｒｄｗａｒｅ  Ｂｏｏｋｓ２','横山直隆','技術評論社');
insert into book values('メカトロニクス入門  メカトロニクスシリーズⅠ入門編','日本機械学会  編','技報堂');
insert into book values('電子工作のはなし（Ⅰ）','佐伯平二','技報堂出版');
insert into book values('電子工作のはなし（Ⅱ）','佐伯平二','技報堂出版');
insert into book values('エレクトロニクスのはなし','佐伯平二','技報堂出版');
insert into book values('電子工作のはなし','佐伯平二','技報堂出版');
insert into book values('無線工學実驗法','千葉茂太郎','共立社');
insert into book values('電子工学の基礎','Ｗ．Ｇ．ダウ','共立社');
insert into book values('人工知能ハンドブック第Ⅰ巻','Ｂａｒｒ，Ａ．  他  編','共立出版');
insert into book values('人工知能ハンドブック第Ⅱ巻','Ｂａｒｒ，Ａ．  他  編','共立出版');
insert into book values('人工知能ハンドブック第Ⅲ巻','Ｂａｒｒ，Ａ．  他  編','共立出版');
insert into book values('グラフ理論の展開と応用','小野寺力男','共立出版');
insert into book values('教養  電子工学通論','長谷川太郎','共立出版');
insert into book values('ディジタル代数学                    大学講座電子工学３','尾崎弘  樹下行三','共立出版');
insert into book values('音響學序説','栗原嘉名芽','共立出版');
insert into book values('グラフ理論','Ｆ．ハラリィ','共立出版');
insert into book values('グラフとダイグラフの理論','ベザット，Ｍ．他','共立出版');
insert into book values('コンピュータによるグラフ理論の応用','カクラ，Ｖ．他','共立出版');
insert into book values('コンピュータによるグラフ理論の応用','カクラ，Ｖ．他','共立出版');
insert into book values('コンピュータによるグラフ理論の応用','カクラ，Ｖ．他','共立出版');
insert into book values('グラフとブール代数','竹中淑子','共立出版');
insert into book values('無線工学','松尾優','共立出版');
insert into book values('無線工學理論','楠瀬雄次郎  千葉茂太郎','共立出版');
insert into book values('最近に於ける無線工學の進歩','','共立出版');
insert into book values('解説エレクトロニクスコース１  電気と回路のはたらき','大島正光  他  編','共立出版');
insert into book values('最新無線通信工學','室住熊三','共立出版');
insert into book values('コンピュータ・アーキテクチャ','坂村健','共立出版');
insert into book values('固体電子素子  モダンサイエンスシリーズ','Ｍｏｒｇａｎ，Ｄ．Ｖ．  Ｈｏｗｅｓ，Ｍ．','共立出版');
insert into book values('ＬＩＳＰによる人工知能の基礎技法','Ｓｈａｐｉｒｏ，Ｓ．Ｃ．','共立出版');
insert into book values('高真空工学                          電子工学講座','須賀太郎','共立出版');
insert into book values('光電管・光電池・セレンセル  照明用放電管  他    電子工学講座','山内二郎  高橋正一','共立出版');
insert into book values('真空管  陰極線管に依る諸測定  放電管に依る諸測定      電子工学講座','小林正次  木下隆博  藤田文太郎','共立出版');
insert into book values('Ｘ線管並にＸ線装置  放電現象        電子工学講座','田中正道  藤田文太郎','共立出版');
insert into book values('格子制御放電管  光電管・セレニウム管の工業応用      電子工学講座','高橋正一','共立出版');
insert into book values('真空管  原子核物理実験              電子工学講座','小林正次  中川重雄','共立出版');
insert into book values('真空管回路                          電子工学講座','千葉茂太郎','共立出版');
insert into book values('電子物理学  高真空工学              電子工学講座','杉浦義勝  須賀太郎','共立出版');
insert into book values('エレクトロニクス講座基礎編２','平山博  川上正光  関口利男','共立出版');
insert into book values('エレクトロニクス講座基礎編３','岸源也  川上正光  末崎輝雄  柳沢健','共立出版');
insert into book values('エレクトロニクス講座基礎編４','奏多野泰吉  高橋茂  高津清一  宇都宮敏一','共立出版');
insert into book values('エレクトロニクス講座基礎編５','志村秀雄  七條祐三  伏見和郎  柴山博  他','共立出版');
insert into book values('エレクトロニクス講座基礎編６','伊藤毅  若井清  西口薫  本荘正人  他','共立出版');
insert into book values('エレクトロニクス講座応用編１','富田義男  星佶兵衛  実吉純一','共立出版');
insert into book values('エレクトロニクス講座応用編２','副島光積  高橋修一  樋渡涓二  鈴木桂二','共立出版');
insert into book values('エレクトロニクス講座応用編３','寺尾満  木村磐  茂木晃  前川高澄  他','共立出版');
insert into book values('エレクトロニクス講座応用編４','和田弘  高橋茂  野田克彦  富田和夫  他','共立出版');
insert into book values('エレクトロニクス講座応用編５','大島康次郎  武藤義一  益子洋一郎  他','共立出版');
insert into book values('エレクトロニクス講座応用編６','富永五郎  小林正次  法貴四郎  石川勇三郎','共立出版');
insert into book values('計算機械','城憲三  他','共立出版');
insert into book values('エレクトロニクス  実験物理学講座７','西野治  他  編','共立出版');
insert into book values('物理のためのエレクトロニクス  共立物理学講座１９','向坂正勝','共立出版');
insert into book values('ＢＡＳＩＣによる電気・電子','須田健二  北原紀之','共立出版');
insert into book values('ＢＡＳＩＣによる電気・電子','須田健二  北原紀之','共立出版');
insert into book values('基礎エレクトロニクス','向坂正勝','共立出版');
insert into book values('無線工学通論','太原彦一','共立出版');
insert into book values('無線工学通論下巻','太原彦一','共立出版');
insert into book values('無線工学通論中巻','太原彦一','共立出版');
insert into book values('無線工学通論下巻','太原彦一','共立出版');
insert into book values('無線工学通論中巻','太原彦一','共立出版');
insert into book values('無線工学通論','','共立出版');
insert into book values('無線工学通論','','共立出版');
insert into book values('無線工学通論','','共立出版');
insert into book values('無線工学通論上巻','太原彦一','共立出版');
insert into book values('無線工学通論中巻','太原彦一','共立出版');
insert into book values('無線工学通論上巻','太原彦一','共立出版');
insert into book values('無線工学通論上巻','太原彦一','共立出版');
insert into book values('無線工学通論中巻','太原彦一','共立出版');
insert into book values('無線工学通論中巻','太原彦一','共立出版');
insert into book values('無線工学通論中巻','太原彦一','共立出版');
insert into book values('高周波工学','森田清','共立出版');
insert into book values('情報科学  パソコンと人工知能','相原恒博  編','共立出版');
insert into book values('ニューロコンピュータへの発想','甘利俊一  戸田正直  松本元  他','共立出版');
insert into book values('計算機科学／ソフトウェア技術講座１７  認知科学と人工知能','安西祐一郎','共立出版');
insert into book values('認知科学と人工知能','安西祐一郎','共立出版');
insert into book values('わかりやすい誤り訂正符号','Ｂ．Ａｒａｚｉ','共立出版');
insert into book values('知識学習のメカニズム  知識情報処理シリーズ２','','共立出版');
insert into book values('計算機入力の人間学','ギルブ，Ｔ．  ワインバーグ，Ｇ．Ｍ．','共立出版');
insert into book values('Ｌｏｔｕｓ１−２−３による科学計算フォーム集','長谷川勝也  川口輝久','共立出版');
insert into book values('並列計算機','Ｒ．Ｗ．Ｈｏｃｋｎｅｙ  他','共立出版');
insert into book values('インターフェースの科学','古川康一  溝口文雄  編','共立出版');
insert into book values('情報科学概論','木村春彦  大藪多可志','共立出版');
insert into book values('ＭＳ−ＤＯＳ                    ＯＳシリーズ４','纐纈一起  鷹野澄','共立出版');
insert into book values('ＭＳ−ＤＯＳ    ＯＳシリーズ４','纐纈一起  鷹野澄','共立出版');
insert into book values('ＯＳ概論  ＯＳシリーズ１','久保秀士','共立出版');
insert into book values('ローカルエリア・ネットワークの基礎知識','ＭｃＮａｍａｒａ，Ｊ．Ｅ．','共立出版');
insert into book values('ＯＳ雑学  ＯＳシリーズ２','前田英明','共立出版');
insert into book values('メンタル・モデルと知識表現  知識情報処理シリーズ１','','共立出版');
insert into book values('メンタル・モデルと知識表現  知識情報処理シリーズ１','','共立出版');
insert into book values('情報処理の基礎                      情報処理入門シリーズ１１','奈良久  武井恵雄','共立出版');
insert into book values('Ｍａｃｉｎｔｏｓｈ              ＯＳシリーズ４','西林瑞夫','共立出版');
insert into book values('二進法  数学ワンポイント双書２１','野崎昭弘','共立出版');
insert into book values('オブジェクト指向  解説とＷＯＯＣ’８５からの論文','鈴木則久  編','共立出版');
insert into book values('ＴＲＯＮを創る','坂村健','共立出版');
insert into book values('コンピュータ・アーキテクチャ  電脳建築学','坂村健','共立出版');
insert into book values('人工知能入門','Ｓｃｏｗｎ，Ｓ．Ｊ．','共立出版');
insert into book values('人工知能','白鳥則郎  菅原研二  木下哲男','共立出版');
insert into book values('自然言語の基礎理論  知識情報処理シリーズ４','','共立出版');
insert into book values('研究者のテイスト  １９９０年代のコンピュータ','鈴木則久','共立出版');
insert into book values('ＯＳ−９／６８０００                ＯＳシリーズ７','高澤嘉光','共立出版');
insert into book values('グラフとブール代数','竹中淑子','共立出版');
insert into book values('ＴＲＯＮ概論','坂村健  編','共立出版');
insert into book values('ＴＲＯＮ概論','坂村健  編','共立出版');
insert into book values('教示学習と知的ＣＡＩ','','共立出版');
insert into book values('計算の基礎理論','細井勉','教育出版');
insert into book values('計算の基礎理論  新しい応用の数学９','細井勉','教育出版');
insert into book values('ディスプレイ工学','Ｌｕｘｅｎｂｅｒｇ，Ｈ．Ｒ．  他  編','近代科学社');
insert into book values('ディスプレイ工学','Ｈ．Ｒ．Ｌｕｘｅｎｂｅｒｇ  他','近代科学社');
insert into book values('低雑音電子回路の設計','Ｍｏｔｃｈｅｎｂａｃｈｅｒ，Ｃ．Ｄ．','近代科学社');
insert into book values('計算機科学入門','ゴールドシュレーガー，Ｌ．  他','近代科学社');
insert into book values('基礎電子工学','Ｈ．Ｖ．Ｈｉｃｋｅｙ  他','近代科学社');
insert into book values('基礎電子工学','Ｈ．Ｖ．Ｈｉｃｋｅｙ  他','近代科学社');
insert into book values('無線従事者標準問題解答集  上級用応用編（下）','無線従事者教育協会  編','近代科学社');
insert into book values('無線従事者問題解答集  上級用基礎編〈上巻〉','無線従事者教育協会  編','近代科学社');
insert into book values('無線従事者標準問題解答集  上級用応用編','無線従事者教育協会  編','近代科学社');
insert into book values('無線従事者標準問題解答集  応用編中','無線従事者教育協会  編','近代科学社');
insert into book values('無線従事者標準問題解答集  上級用応用編〈上巻〉','','近代科学社');
insert into book values('無線工学','無線従事者協会  編','近代科学社');
insert into book values('無線従事者受験ハンドブック','無線従事者教育協会  編','近代科学社');
insert into book values('オペレーティングシステム            コンピュータサイエンス大学講座２３','村岡洋一','近代科学社');
insert into book values('オペレーティングシステム','村岡洋一','近代科学社');
insert into book values('教養のための情報科学入門','中村義作  清水道夫','近代科学社');
insert into book values('一技用  空中線及び電波の伝わり方','大岡茂','近代科学社');
insert into book values('一技用  空中線及び電波の伝わり方','大岡茂','近代科学社');
insert into book values('考えるコンピュータ','ラファエル，Ｂ．','近代科学社');
insert into book values('人工知能','サイモンズ，Ｇ．Ｌ．','近代科学社');
insert into book values('電子工学','Ｔ．Ｓ．Ｇｒａｙ','近代科学社');
insert into book values('電子工学','Ｔ．Ｓ．Ｇｒａｙ','近代科学社');
insert into book values('電子工学（下）','Ｔ．Ｓ．Ｇｒａｙ','近代科学社');
insert into book values('電子工学（上）','Ｔ．Ｓ．Ｇｒａｙ','近代科学社');
insert into book values('人工知能の基礎知識  コンピュータサイエンス大学講座２０','太原育夫','近代科学社');
insert into book values('自然言語処理入門  コンピュータサイエンス大学講座１９','東条敏','近代科学社');
insert into book values('エキスパートシステムの設計','Ｓ．Ｍ．ワイス  Ｃ．Ａ．クリコフスキ','近代科学社');
insert into book values('グラフ理論入門','ウィルソン，Ｒ．Ｊ．','近代科学社');
insert into book values('計算尺の使い方','村上次郎','金園社');
insert into book values('システム思考の源流と発展','佐藤敬三  北原貞輔  他','九州大学出版会');
insert into book values('情報の科学  シャノン情報からファジィ情報へ','大友詔雄  田中幸雄  清藤正','桑園学園情報科学セ');
insert into book values('実用  電子公式集','阿部節次','啓学出版');
insert into book values('ＣＰ／Ｍ−８０マイクロソフトユーティリティ徹底活用','黒瀬能聿','啓学出版');
insert into book values('ＯＳ−９  ＵＳＥＲ  ＮＯＴＥＳ','ディブル，ピーター，Ｃ．','啓学出版');
insert into book values('高性能コンピュータ入門','Ｉｂｂｅｔｔ，Ｒ．Ｎ．','啓学出版');
insert into book values('コンピュータ・グラフィックス基本ソフトウェア','Ｈｏｐｇｏｏｄ，Ｆ．Ｒ．Ａ．  他','啓学出版');
insert into book values('マイクロコンピュータ・グラフィックス','マイヤーズ，ロイ，Ｅ．','啓学出版');
insert into book values('初めて学ぶ人のための  人工知能入門','グラハム，ネイル','啓学出版');
insert into book values('マイコンのためのやさしいインターフェース製作入門','ビショップ，オーウェン','啓学出版');
insert into book values('マイコンのためのやさしいインターフェース製作入門','ビショップ，オーウェン','啓学出版');
insert into book values('人工知能ＢＡＳＩＣ                  ＢＡＳＩＣ理工学応用シリーズ６','Ｍ．ジェームス','啓学出版');
insert into book values('ポスト・ディジタルエレクトロニクス','Ｐｅｔｔｉｔ，Ｆ．Ｒ．','啓学出版');
insert into book values('ニューラルネットワークの設計','Ｅ．リートマン','啓学出版');
insert into book values('Ｐｒｏｌｏｇで学ぶＡＩ手法  推論システムと自然言語処理','高野真','啓学出版');
insert into book values('図解  人工知能入門','戸内順一','啓学出版');
insert into book values('情報学講義ノート１','岡澤和世','敬文堂');
insert into book values('情報学講義ノート２','岡澤和世','敬文堂');
insert into book values('テクノバブル','Ｊ．Ａ．バリー','工学社');
insert into book values('ザ・パソコンアニメーション','野地朱真','工学図書');
insert into book values('固体電子材料','小沼稔','工学図書');
insert into book values('遊びのエレクトロニクス  マイコンが開く娯楽芸術の世界','中原紀','工業調査会');
insert into book values('遊びのエレクトロニクス  マイコンが開く娯楽芸術の世界','中原紀','工業調査会');
insert into book values('Ｃ言語パソコンＣＡＤ・ＣＧプログラム集','Ｃ＆ＣＧ研究会グループ  編','工業調査会');
insert into book values('Ｃ言語によるパソコンＣＡＤ・ＣＧ  プログラム例に学ぶグラフィクス手法','Ｃ＆ＣＧ研究会グループ  編','工業調査会');
insert into book values('マイクロ波工学の基礎','牧本利夫  松尾幸人','広川書店');
insert into book values('情報源  ’８１〜’８２年版','講談社  編','講談社');
insert into book values('ゆらぎの世界  自然界の１／ｆゆらぎの不思議  ブルーバックスＢ４４２','武者利光','講談社');
insert into book values('電波技術への招待                    ブルーバックスＢ３５０','徳丸仁','講談社');
insert into book values('電波技術への招待                    ブルーバックスＢ３５０','徳丸仁','講談社');
insert into book values('電波に強くなる                      ブルーバックスＢ４３６','徳丸仁','講談社');
insert into book values('化学と医学のための電子工学','バッサス，Ｂ．Ｈ．  ユーウィング，Ｇ．Ｗ','講談社');
insert into book values('エレクトロニクスからの発想          ブルーバックスＢ４９１','菊池誠','講談社');
insert into book values('コンピュータもびっくり！  速算１００のテクニック  これでキミも計算名人','中村義作','講談社');
insert into book values('パソコン・ホビー工作入門  ＢＡＳＩＣでメカトロニクスを楽しむ','西田和明','講談社');
insert into book values('人工知能のＡＢＣ                    ＡＩの考え方・学び方・取り入れ方','和多田作一郎','講談社');
insert into book values('１６ビットパソコンを使いこなす','脇秀世','講談社');
insert into book values('ＭＳ−ＤＯＳとは何か','脇秀世','講談社');
insert into book values('人工知能と知的ＣＡＩシステム','スリーマン，Ｄ．  ブラウン，Ｊ．Ｓ．  編','講談社サイエンティ');
insert into book values('情報科学基礎論','成沢広行','高文堂出版社');
insert into book values('点と線の世界  三共科学選書５','奥野隆史  高森寛','三共出版');
insert into book values('真空管工学','笹尾利男','三共出版');
insert into book values('情報処理技術者のためのコンピュータ英語','青柳忠克  掛井幹雄  大島正弘','産業図書');
insert into book values('電子工学入門演習','山口修広  馬場秀三郎  石坂陽之助','産業図書');
insert into book values('電気通信  無線通信編','福田滋夫','産業図書');
insert into book values('ＰＤＰモデル                        認知科学とニューロン回路網の探索','Ｄ．Ｅ．ラメルハート  他','産業図書');
insert into book values('ＰＤＰモデル                        認知科学とニューロン回路網の探索','Ｄ．Ｅ．ラメルハート  他','産業図書');
insert into book values('適応アルゴリズム  離散と連続、真髄へのアプローチ','新中新二','産業図書');
insert into book values('電子工学入門演習','山口修弘  馬場秀三郎  石坂陽之助','産業図書');
insert into book values('電子工学入門演習','山口修広  馬場秀三郎  石坂陽之助','産業図書');
insert into book values('オプトエレクトロニクスへの挑戦','日本科学技術振興財団ＥＣＥ懇談会  編','産業調査会');
insert into book values('メカトロシステム事典','メカトロシステム事典編集委員会  編','産業調査会');
insert into book values('産業用アクチュエーター（応用技術・利用技術）  メカトロシリーズⅢ','','産業調査会');
insert into book values('光エレクトロニクス事典','光エレクトロニクス事典編集委員会  編','産業調査会');
insert into book values('機械技術者のためのエレクトロニクス  素子編  エンジニヤシリーズ６','杉田稔','産報出版');
insert into book values('スイチッチングレギュレータ  電子科学ブルーバックス','嶋村弘則','産報出版');
insert into book values('物性電子工学','中村新太郎','実教出版');
insert into book values('高周波科学','八木秀次','修教社');
insert into book values('無線工学','門岡速雄','修教社書院');
insert into book values('グラフィクス  改訂版','井上智','秀和システムトレー');
insert into book values('ＯＳ−９／６８０９  ＵＴＩＬＩＴＩＥＳ','金井隆','秀和システムトレー');
insert into book values('ＯＳ−９／６８０９  Ｉ／Ｏ  解析マニュアル','箕原辰夫  編著','秀和システムトレー');
insert into book values('ＦＭ７  Ｆ−ＢＡＳＩＣ  解析マニュアル  フェーズⅠ  基礎編','中村英都','秀和システムトレー');
insert into book values('ＦＭ７  Ｆ−ＢＡＳＩＣ  解析マニュアル  フェーズⅡ  探究編','箕原辰夫  菊池寿  南泰浩','秀和システムトレー');
insert into book values('ＦＭ７  Ｆ−ＢＡＳＩＣ  解析マニュアル  フェーズⅢ  サブシステム編','','秀和システムトレー');
insert into book values('ＯＳ−９  Ｌｅｖｅｌ１  解析マニュアル','金井豊','秀和システムトレー');
insert into book values('ＯＳ−９／６８０９  Ｌｅｖｅｌ２  解析マニュアル','金井豊  編著','秀和システムトレー');
insert into book values('マニュアルでわからなかった人のための  ＯＳ−９入門','那須正夫','秀和システムトレー');
insert into book values('３Ｄスーパーグラフィックス','伊藤貢司  伊藤直基','秀和システムトレー');
insert into book values('３Ｄスーパーグラフィックス','伊藤貢司  伊藤直基','秀和システムトレー');
insert into book values('コンピュータ画像処理                エレクトロニクス選書','安居院猛  中嶋正之','秋葉出版');
insert into book values('はじめてのあっぷる','ハイテクノロジー・コミュニケーションズ','小学館');
insert into book values('電子工学及電子管','日置高志','尚賢堂');
insert into book values('グラフ理論解説','服部嘉雄  小澤孝夫','昭晃堂');
insert into book values('オペレーティングシステムの基礎','亀田壽夫','昭晃堂');
insert into book values('回路のためのグラフ理論','梶谷洋司','昭晃堂');
insert into book values('量子エレクトロニクス','小川徹','昭晃堂');
insert into book values('量子エレクトロニクス','小川徹','昭晃堂');
insert into book values('量子エレクトロニクス','小川徹','昭晃堂');
insert into book values('真空・気体・半導体電子工学','池田吉尭','昭晃堂');
insert into book values('電子工学要論','石井正博','昭晃堂');
insert into book values('電子工学要論','石井正博','昭晃堂');
insert into book values('電子工学要論','石井正博','昭晃堂');
insert into book values('電子工学要論','石井正博','昭晃堂');
insert into book values('基礎電子工学Ⅰ','伊藤糾次','昭晃堂');
insert into book values('基礎電子工学Ⅱ','伊藤糾次  他','昭晃堂');
insert into book values('基礎電子工学（１）','伊藤糾次','昭晃堂');
insert into book values('基礎電子工学Ⅱ','伊藤糾次','昭晃堂');
insert into book values('オプトエレクトロニックデバイス','青木昌治  編著','昭晃堂');
insert into book values('知識の表現と利用  人工知能シリーズ８','辻井潤一','昭晃堂');
insert into book values('知識の表現と利用','辻井潤一','昭晃堂');
insert into book values('音と音波          基礎物理学選書４','小橋豊','裳華房');
insert into book values('音と音波  基礎物理学選書４','小橋豊','裳華房');
insert into book values('エレクトロニクスの基礎  物理学選書１  全訂版','霜田光一','裳華房');
insert into book values('薄膜  応用物理学選書３','金原粲  藤原英夫','裳華房');
insert into book values('エレクトロニクスの基礎','霜田光一','裳華房');
insert into book values('自己組織性の情報科学  エヴォルーショニストのウィーナー的自然観','吉田民人','新曜社');
insert into book values('グラフ理論の展開と応用  数学ライブラリー３０','小野寺力男','森北出版');
insert into book values('グラフ理論の展開と応用  数学ライブラリー３０','小野寺力男','森北出版');
insert into book values('新編  無線通信工学Ⅰ','河野政治','森北出版');
insert into book values('無線通信工学Ⅰ  新編','河野政治','森北出版');
insert into book values('無線通信工学Ⅰ  新編','河野政治','森北出版');
insert into book values('新編  無線通信工学Ⅱ','河野政治','森北出版');
insert into book values('無線通信工学Ⅱ  新編','河野政治','森北出版');
insert into book values('無線通信工学Ⅱ  新編','河野政治','森北出版');
insert into book values('新編  無線通信工学Ⅲ','河野政治','森北出版');
insert into book values('無線通信工学Ⅲ  新編','河野政治','森北出版');
insert into book values('新編  無線通信工学Ⅰ','河野政治','森北出版');
insert into book values('新編  無線通信工学Ⅱ','河野政治','森北出版');
insert into book values('パソコンファイル変換法','二之宮弘  竹迫一雄','森北出版');
insert into book values('グラフ理論の基礎','小野寺力男','森北出版');
insert into book values('電子工学・通信工学計算法','山本勇  河野政治','森北出版');
insert into book values('信号検出理論','ハンコック，Ｊ．  ウィンツ，Ｐ．','森北出版');
insert into book values('電子工学概論','石川太郎','森北出版');
insert into book values('電子工学概論','石川太郎','森北出版');
insert into book values('電子力学  電器電子工学基礎講座４','川村光男','森北出版');
insert into book values('バーローの数表','','森北出版');
insert into book values('集成万能数表','','森北出版');
insert into book values('電子デバイス入門','Ｆ．Ｒ．コナー','森北出版');
insert into book values('エレクトロニクスを支える材料  基礎から応用まで','丹野頼元  編','森北出版');
insert into book values('エレクトロニクスへの招待','','森北出版');
insert into book values('エレクトロニクスへの招待','丹野頼元  編著','森北出版');
insert into book values('電気工学概論  電子工学編','半澤正夫  中野光雄','森北出版');
insert into book values('新編  無線通信工学（Ⅰ）','河野政治','森北出版');
insert into book values('新編  無線通信工学（Ⅱ）','河野政治','森北出版');
insert into book values('新編  無線通信工学（Ⅲ）','河野政治','森北出版');
insert into book values('光エレクトロニクス','上林利生  貴堂靖昭','森北出版');
insert into book values('光エレクトロニクス','上林利生  貴堂靖昭','森北出版');
insert into book values('電子工学実験','内藤喜之  熊谷正純','森北出版');
insert into book values('オプトエレクトロニクス入門','桜庭一郎','森北出版');
insert into book values('エレクトロニクスを支える材料  基礎から応用まで','丹野頼元  編','森北出版');
insert into book values('メカトロニクスへの招待','丹野頼元  編','森北出版');
insert into book values('舶用電子工学概論','西谷芳雄','成山堂');
insert into book values('百万人のエレクトロニクス','電子工学研究会  編','成山堂');
insert into book values('曲線・グラフ総覧','秋田秀三  他','聖文社');
insert into book values('図説  エレクトロニクス技術','中込八郎','聖文堂');
insert into book values('ラジオ  アマチュア  ハンドブック','日本アマチュア無線連盟','誠文堂');
insert into book values('無線工学（中）','稲田三之助','誠文堂新光社');
insert into book values('わかるＣＰ／Ｍアセンブラとファンクションコール','伏見良隆','誠文堂新光社');
insert into book values('パソコンは３日で打てる','山本嘉虎','誠文堂新光社');
insert into book values('図解  エレクトロニクスの製作ＡＢＣ','泉弘志','誠文堂新光社');
insert into book values('無線用基礎計算問題解答集  無線と実験編','','誠文堂新光社');
insert into book values('無線用基礎計算問題解答集  無線と実験編','','誠文堂新光社');
insert into book values('学校では教えないハイテク素子','奥澤清吉  奥澤熈','誠文堂新光社');
insert into book values('ＦＭステレオ製作読本','初歩のラジオ  編','誠文堂新光社');
insert into book values('東芝電子管ハンドブック  受信管ＴＶ用ブラウン管編','','誠文堂新光社');
insert into book values('東芝電子管ハンドブック  受信管・ＴＶ用ブラウン管編２','東京芝浦電気株式会社  編','誠文堂新光社');
insert into book values('音の世界','Ｗ．Ｈ．ブラッグ','創元社');
insert into book values('マイコン・パソコンの話','岩尾達男','創元社');
insert into book values('文字処理のための計算機','古郡廷治','総研出版');
insert into book values('高速スイッチングレギュレータ','清水和男','総合電子出版');
insert into book values('オプトエレクトロニクスの活用  電子化ブックス','服部肇','大河出版');
insert into book values('電子通信の現状と展望第３巻  総合レビュー電子通信の現状と展望シリーズ','科学技術庁  編','大蔵省印刷局');
insert into book values('電子技術の基礎知識','電子技術研究会  編','大蔵省印刷局');
insert into book values('エレクトロニクス材料                新化学ライブラリー','平野正浩  北沢宏一','大日本図書');
insert into book values('１０年後  人工知能が社会を変える','渡邊茂  矢田光治','第一企画出版');
insert into book values('ディジタル技術','山本外史','朝倉');
insert into book values('計算法        基礎工業数学講座５','渡部信夫','朝倉書店');
insert into book values('電子・通信工学実験','池谷和夫','朝倉書店');
insert into book values('電波工学入門','松本欣二','朝倉書店');
insert into book values('量子エレクトロニクス','日本物理学会  編','朝倉書店');
insert into book values('量子エレクトロニクス','日本物理学会  編','朝倉書店');
insert into book values('電気通信Ⅱ','虫明康人','朝倉書店');
insert into book values('電気通信Ⅱ  電気工学基礎講座１１','虫明康人','朝倉書店');
insert into book values('固体表示装置  電子工学シリーズ２','伊吹順章','朝倉書店');
insert into book values('電子工学','榊米一郎  編','朝倉書店');
insert into book values('量子電子工学  基礎と原理','武者利光','朝倉書店');
insert into book values('電子工学概論','黒部貞一  小川吉彦','朝倉書店');
insert into book values('電子工学通論  増補版','榊米一郎','朝倉書店');
insert into book values('電気工学基礎論','仁平幸治  武藤信男  坪井常世','朝倉書店');
insert into book values('電子通信工学実験','池谷和夫','朝倉書店');
insert into book values('電子回路','松尾正之','朝倉書店');
insert into book values('電波工学入門','松本欣二','朝倉書店');
insert into book values('４次元グラフィクス  高次元ＣＧへの道','宮崎興二  石原慶一','朝倉書店');
insert into book values('コンピュータ・グラフィックス  情報化社会と映像','水上孝一','朝倉書店');
insert into book values('音の科学','難波精一郎  後藤敏幸  橘秀樹  他','朝倉書店');
insert into book values('教師のための情報技術入門','日本産業技術教育学会  編','朝倉書店');
insert into book values('教師のための情報技術入門','日本産業技術教育学会情報分科会  編','朝倉書店');
insert into book values('情報環境学','大橋力','朝倉書店');
insert into book values('オプトエレクトロニクス','','朝倉書店');
insert into book values('数値計算Ⅰ','新谷尚義','朝倉書店');
insert into book values('電子回路','吉田重知','朝倉書店');
insert into book values('近代  電子工学実験','安濃恒友  横戸健一  小野寺力男','電機書院');
insert into book values('無線通信・測定制御装置','電気学会通信教育会  編','電気学会');
insert into book values('ジョセフソン効果  基礎と応用','電気学会クライオエレクトロニクス常置委員','電気学会');
insert into book values('電子工学概論','電気学会通信教育会','電気学会');
insert into book values('無線通信','電子学会通信教育会','電気学会');
insert into book values('基礎電子工学  電気学会大学講座','電気学会通信教育会  編','電気学会');
insert into book values('現場マンのためのディジタル技術の原理と実際','茂木晃','電気書院');
insert into book values('近代電子工学大講座１０  近代電子工学実験','安濃恒友  他','電気書院');
insert into book values('近代  電子工学実験','安濃恒友  横戸健一  小野寺力男','電気書院');
insert into book values('近代電子工学大講座３  近代固体電子工学','田中哲郎','電気書院');
insert into book values('近代電子工学大講座９  近代応用電子工学','井上勅夫','電気書院');
insert into book values('電気通信','電気学会  編','電気書院');
insert into book values('高周波・通信工学','山本勇  關英男','電気書院');
insert into book values('無線通信','米山正雄','電気書院');
insert into book values('無線通信','米山正雄','電気書院');
insert into book values('ファジィ・エキスパートシステム  理論と実践','Ｗ．Ｍ．サイラー','電気書院');
insert into book values('近代  固体電子工学','田中哲郎','電気書院');
insert into book values('電気通信術','加藤芳雄','電子工学社');
insert into book values('情報システムの信頼性','岩垂好裕','電子情報通信学会');
insert into book values('エレクトロニクスのための材料開発','三村栄紀  松島裕一','電子情報通信学会');
insert into book values('電子物性工学  電子通信学会大学講座６','電子通信学会  編','電子通信学会');
insert into book values('電子通信ハンドブック','電子通信学会  編','電子通信学会');
insert into book values('通信運用と特殊通信概論','野間逸郎','電波振興会');
insert into book values('通信運用と特殊通信概論','野間逸郎','電波振興会');
insert into book values('通信運用と特殊通信概論','野間逸郎','電波振興会');
insert into book values('無線工学１  基礎篇','','電波振興会');
insert into book values('無線工学Ⅱ  無線機器編  上巻  電子管回路','','電波振興会');
insert into book values('無線工学２  無線測定篇','','電波振興会');
insert into book values('無線工学Ⅱ  無線機器編  中巻  無線通信方式，無線送信機','','電波振興会');
insert into book values('無線工学Ⅱ  無線機器編上  電子管回路','','電波振興会');
insert into book values('無線工学Ⅱ  無線機器編中  無線通信方式、無線送信機','','電波振興会');
insert into book values('無線工学Ⅱ  無線機器編下  受信機、電源、部品材料','','電波振興会');
insert into book values('無線工学３  空中線系および電波伝搬篇','','電波振興会');
insert into book values('無線工学Ⅱ  無線機器編  下巻  受信機，電源，部品材料','','電波振興会');
insert into book values('無線工学Ⅲ  無線測定篇','','電波振興会');
insert into book values('無線工学の基礎','鈴木正','電波振興会');
insert into book values('無線工学の基礎','池田裕之','電波振興会');
insert into book values('第２級無線通信士国家試験問題解答集','電波振興会  編','電波振興会');
insert into book values('最新  無線学','','電波振興会');
insert into book values('無線機器と無線測定','','電波振興会');
insert into book values('無線工学の基礎とその応用','','電波振興会');
insert into book values('無線工学Ⅰ  基礎編','','電波振興会');
insert into book values('無線機器と無線測定','電波振興会  編','電波振興会');
insert into book values('無線送信機','電波振興会  編','電波振興会');
insert into book values('特殊無線技士必携','電波振興会','電波振興会');
insert into book values('基礎無線工学','岡登博美','電波振興会');
insert into book values('基礎無線工学','岡登博美','電波振興会');
insert into book values('基礎無線工学','岡登博美','電波振興会');
insert into book values('真空管とトランジスター','富田稔','電波振興会');
insert into book values('ＰＣ−９８０１  Ｅ／Ｆ  ＭＳ−ＤＯＳ入門','塚越一雄','電波新聞社');
insert into book values('無線・通信入門基本１８章','大浦和夫','電波新聞社');
insert into book values('スーパーパソコン','青野忠夫','電波新聞社');
insert into book values('パソコン・グラフィックス','成沢広行','電波新聞社');
insert into book values('たのしい電子工作Ｎｏ２  ラジオの製作','月刊「ラジオの製作」  編','電波新聞社');
insert into book values('ディジタル情報処理の基礎理論','斎藤正男  篠崎寿夫  根本幾','東海大学出版会');
insert into book values('エレクトロニクス物語','クバルキン，エリ  レウ゛ィーチン，イエ','東京図書');
insert into book values('薄膜の基本技術  物理工学実験５','金原粲','東京大学出版会');
insert into book values('機械の知人間の知                    認知科学選書２０','辻井潤一  安西祐一郎','東京大学出版会');
insert into book values('機械の知人間の知                    認知科学選書２０','辻井潤一  安西祐一郎','東京大学出版会');
insert into book values('エレクトロニクスの世界','兵頭正明  垂井忠明','東京電機大学出版局');
insert into book values('電磁妨害と防止対策','荒木庸夫','東京電機大学出版局');
insert into book values('無線工学の基礎Ⅰ','松原孝之','東京電機大学出版局');
insert into book values('電気基礎  交流回路編','','東京電機大学出版局');
insert into book values('電子工学一般','秋富勝  岩本洋  河崎隆一','東京電機大学出版局');
insert into book values('計算尺の理論と使用方','高岡大','東京電機大学出版局');
insert into book values('計算尺基本演習','高岡大','東京電機大学出版局');
insert into book values('音の百科','松下電器音響研究所  編','東洋経済新報社');
insert into book values('先端エレクトロニクス百科','三菱電機ソシオテックス研究会  編','東洋経済新報社');
insert into book values('任天堂のファミリーベーシック入門','テクノポリス編集部  編著','徳間書店');
insert into book values('便利なＣＦ・ＰＦによる  計算尺の使い方','金田数正','内田老鶴圃新社');
insert into book values('ネットワーク理論  ＯＲライブラリー１２','伊理正夫  古林隆','日科技連');
insert into book values('人工知能のはなし','','日刊工業新聞');
insert into book values('エレクトロニクスはいかにして創られたか','岩田倫典','日刊工業新聞社');
insert into book values('フェライトエレクトロニクス','小西良弘  小林成彬  辻俊郎  編著','日刊工業新聞社');
insert into book values('薄膜作成の基礎','麻蒔立男','日刊工業新聞社');
insert into book values('マイコンエイジのＡ／Ｄ・Ｄ／Ａ変換技術','相良岩男','日刊工業新聞社');
insert into book values('マイコンエイジのＡ／Ｄ・Ｄ／Ａ変換技術','相良岩男','日刊工業新聞社');
insert into book values('ディジタルのはなし','相良岩男','日刊工業新聞社');
insert into book values('エレクトロニクス産業・社会を変える','','日刊工業新聞社');
insert into book values('絵でみるエレクトロニクス読本','緒方健二','日刊工業新聞社');
insert into book values('マイコンとセンサのインターフェイス技術  基礎編','村田裕','日刊工業新聞社');
insert into book values('マイコンとセンサのインターフェイス技術  応用編','村田裕','日刊工業新聞社');
insert into book values('ＲＳ２３２Ｃインターフェイスの使い方','松田稔  山本正樹','日刊工業新聞社');
insert into book values('メカトロニクスのはなし','舘','日刊工業新聞社');
insert into book values('高周波通信工学','河野政治','日刊工業新聞社');
insert into book values('実験値計算法','浅野徹','日刊工業新聞社');
insert into book values('ソフトウェア工学','市川忠男','日刊工業新聞社');
insert into book values('マンガ  エレクトロニクスのはなし','相良岩男  しいやみつのり','日刊工業新聞社');
insert into book values('オプトロニック・デバイスの使い方','志水英二  高橋晴雄','日刊工業新聞社');
insert into book values('人工現実感','舘すすむ','日刊工業新聞社');
insert into book values('ＲＳ２３２Ｃインターフェィス事例集','山本正樹  松田稔','日刊工業新聞社');
insert into book values('ＲＳ２３２Ｃインターフェイス事例集','山本正樹  松田稔','日刊工業新聞社');
insert into book values('分散型オペレーティング・システムの設計','Ｐ．Ｊ．Ｆｏｒｔｉｅｒ','日経ＢＰ社');
insert into book values('オペレーティング・システムの理論','Ｃｏｆｆｍａｎ，Ｅ．Ｇ．Ｊｒ  他','日本コンピュータ協');
insert into book values('ソフトウェアの構造化設計法','Ｙｏｕｒｄｏｎ，Ｅ．  他','日本コンピュータ協');
insert into book values('電子機器用固定抵抗器の試験方法  ＪＩＳｃ５２０２','','日本規格協会');
insert into book values('電子機器用小形電源変圧器        ＪＩＳｃ６４３６','','日本規格協会');
insert into book values('ソフトウェアの知識','山本欣子','日本経済新聞社');
insert into book values('メカトロニクスのことがわかる本','鶴岡重成  編著','日本実業出版社');
insert into book values('ＴＲＯＮで変わるコンピュータ','坂村健','日本実業出版社');
insert into book values('新版  エレクトロニクスのことがわかる本','鈴木良次','日本実業出版社');
insert into book values('データ・ブック  オプトエレクトロニクスデバイス NEPOCシリーズ 1990/91','日本電気株式会社半導体応用技術本部  編','日本電気株式会社');
insert into book values('エレクトロニクス革命','オーム，ミカエル','日本能率協会');
insert into book values('計算の効率化とその限界  数学セミナー増刊  入門現代の数学１３','伊理正夫  野崎昭弘  野下浩平  編著','日本評論社');
insert into book values('計算の効率化とその限界  数学セミナー増刊  入門現代の数学１３','伊理正夫  野崎昭弘  野下浩平  編著','日本評論社');
insert into book values('音  その形態と物理  ＮＨＫブックス５０','竹内龍一','日本放送出版協会');
insert into book values('エレクトロンの話                    ＮＨＫブックス８２','関英男','日本放送出版協会');
insert into book values('實用放送工學（下）','日本放送協会  編','日本放送出版協会');
insert into book values('ラジオ工学１','F.E.Terman','日本放送出版協会');
insert into book values('ラジオ工学２','F.E.Terman','日本放送出版協会');
insert into book values('ラジオ工学３','F.E.Terman','日本放送出版協会');
insert into book values('ラジオ工学４','F.E.Terman','日本放送出版協会');
insert into book values('たのしいエレクトロニクス  ホビーテクニック２６','田島定爾','日本放送出版協会');
insert into book values('ラジオ工學第１巻','Frederick,E.Terman','日本放送出版協会');
insert into book values('ラジオ工學第２巻','Frederick,E.Terman','日本放送出版協会');
insert into book values('ラジオ工學第１巻','Frederick,E.Terman','日本放送出版協会');
insert into book values('便利な電源','丹羽一夫','日本放送出版協会');
insert into book values('音  その形態と物理','竹内龍一','日本放送出版協会');
insert into book values('電子工学概論','宇佐美晶  曽根福保','日本理工出版会');
insert into book values('グラフ理論とネットワーク  基礎と応用','バサッカー，Ｒ．Ｇ．  サーティ，Ｔ．Ｌ．','培風館');
insert into book values('グラフ理論とネットワーク','バサッカー，Ｒ．Ｇ．  サーティ，Ｔ．Ｌ．','培風館');
insert into book values('振動論  新物理学シリーズ３','戸田盛和','培風館');
insert into book values('振動論  新物理学シリーズ３','戸田盛和','培風館');
insert into book values('振動論  新物理学シリーズ３','戸田盛和','培風館');
insert into book values('グラフと追跡','坂井忠次','培風館');
insert into book values('グラフ理論入門','ボロバッシュ，Ｂ．','培風館');
insert into book values('量子エレクトロニクス入門  新物理学シリーズ１１','宅間宏','培風館');
insert into book values('電子工学演習１  基礎とデバイス','西巻正郎  他  編','培風館');
insert into book values('電子工学演習２  回路と応用','西巻正郎  他  編','培風館');
insert into book values('電子工学演習１','西巻正郎  他編','培風館');
insert into book values('電子工学演習２','西巻正郎  他編','培風館');
insert into book values('数理統計学概説','佐藤良一郎','培風館');
insert into book values('オートマトンと計算可能性  情報処理シリーズ９','有川節夫  宮野悟','培風館');
insert into book values('超高速光エレクトロニクス','末田正  神谷武志  編','培風館');
insert into book values('スーパーコンピュータ','日本物理学会  編','培風館');
insert into book values('計算尺の理論','唐木英雄','博文社');
insert into book values('社会情報学のデザイン  すべての現代人への新しい提案','日比野省三  加藤晴明','福村出版');
insert into book values('パソコンで学ぶパターン認識と図形処理','上坂吉則  太原育夫','文一総合出版');
insert into book values('音楽と科學','今堀克巳','北方出版');
insert into book values('やさしいコンピュータの話            毎日ヤング・サイエンス選書３','竪川豪','毎日新聞社');
insert into book values('応用数学  数値計算法','田中明雄','槙書店');
insert into book values('グラフ論要説','浜田隆資','槙書店');
insert into book values('グラフ論要説','浜田隆資','槙書店');
insert into book values('電子工学（上）','Ｔ．Ｓ．Ｇｒａｙ','無線従事者教育協会');
insert into book values('電子工学（下）','Ｔ．Ｓ．Ｇｒａｙ','無線従事者教育協会');
insert into book values('無線通信士問題解答集','','無線従事者教育協会');
insert into book values('無線通信士問題解答集','','無線従事者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集３','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集１','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集３','','無線従者教育協会');
insert into book values('無線従事者国家試験  科目分析問題解答集２','','無線従者教育協会');
insert into book values('基礎  電子工学上巻','ヒッキー，ヘンリー，Ｖ．  ビラン，Ｗ．Ｍ','無線従者教育協会');
insert into book values('基礎  電子工学下巻','ヒッキー，ヘンリー，Ｖ．  ビラン，Ｗ．Ｍ','無線従者教育協会');
insert into book values('初学者のための電子工学','片山満澄','理工学社');
insert into book values('基礎の無線工学','藤倉文夫','理工学社');
insert into book values('ラジオ・ステレオ実技百科','樋口千代造','理工学社');
insert into book values('きこえない音  超音波の話','クドリャフツェフ','理論社');
insert into book values('日本語マルチプラン活用法  改訂版','岡崎光男  飯島弘文','廣済堂出版');
insert into book values('精解演習  電子工学Ⅰ','野畑金弘','廣川書店');
insert into book values('精解演習  電子工学Ⅰ','野畑金弘','廣川書店');
insert into book values('精解演習  電子工学Ⅰ','野畑金弘','廣川書店');
